# Generated by Django 2.2.3 on 2019-07-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20190727_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_posted',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='date_posted',
        ),
    ]
