# Generated by Django 2.2.10 on 2020-07-29 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20190819_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('date_posted',)},
        ),
    ]
