# Generated by Django 2.2.3 on 2019-07-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190723_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Users Profiles'},
        ),
    ]
