# Generated by Django 2.2.3 on 2019-07-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190723_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='/profile_pics/default.png', upload_to='profile_pics'),
        ),
    ]
